-- Drop tables if they exist to avoid conflicts
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100),
    CITY VARCHAR2(100),
    STATE VARCHAR2(50)
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(8, 2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Insert sample customers
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE) VALUES (1, 'John Smith', 'Atlanta', 'Georgia');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE) VALUES (2, 'Jane Doe', 'Miami', 'Florida');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE) VALUES (3, 'Alice Johnson', 'Orlando', 'Florida');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE) VALUES (4, 'Bob Brown', 'Savannah', 'Georgia');
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE) VALUES (5, 'Charlie Davis', 'Seattle', 'Washington');

-- Insert sample orders
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (1, 1, SYSDATE - INTERVAL '5' DAY, 85.00);
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (2, 2, SYSDATE - INTERVAL '2' DAY, 100.00);
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (3, 3, SYSDATE - INTERVAL '40' DAY, 75.00);
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (4, 4, SYSDATE - INTERVAL '1' DAY, 90.00);
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (5, 5, SYSDATE - INTERVAL '10' DAY, 55.00);

SET LINESIZE 100
SET PAGESIZE 50
SET TRIMSPOOL ON
SET HEADING ON
SET FEEDBACK OFF


SELECT 
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.CITY,
    C.STATE,
    O.ORDER_ID,
    O.ORDER_DATE,
    O.TOTAL_AMOUNT
FROM 
    CUSTOMERS C
JOIN 
    ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE 
    (C.STATE = 'Georgia' OR C.STATE = 'Florida')
    AND O.TOTAL_AMOUNT > 80
    AND O.ORDER_DATE >= SYSDATE - INTERVAL '30' DAY; 

prompt Jalu Chaudhary

