-- Drop tables if they exist
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE AUTHORS CASCADE CONSTRAINTS;

-- Create AUTHORS table
CREATE TABLE AUTHORS (
    AUTHOR_ID NUMBER PRIMARY KEY,
    AUTHOR_NAME VARCHAR2(100)
);

-- Create BOOK table
CREATE TABLE BOOK (
    BOOK_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100),
    AUTHOR_ID NUMBER,
    RETAIL_PRICE NUMBER(8,2),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- Insert authors
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME) VALUES (1, 'Lisa White');
INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME) VALUES (2, 'John Smith');

-- Insert books with varying prices
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_ID, RETAIL_PRICE) 
VALUES (1, 'Mohobat', 1, 55.00);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_ID, RETAIL_PRICE) 
VALUES (2, 'Maya', 1, 75.00);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_ID, RETAIL_PRICE) 
VALUES (3, 'cooking', 2, 45.00);
INSERT INTO BOOK (BOOK_ID, TITLE, AUTHOR_ID, RETAIL_PRICE) 
VALUES (4, 'computer', 1, 90.00);  

SELECT 
    B.TITLE,
    B.RETAIL_PRICE
FROM 
    BOOK B
JOIN 
    AUTHORS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE 
    A.AUTHOR_NAME = 'Lisa White'
ORDER BY 
    B.RETAIL_PRICE DESC
FETCH FIRST 1 ROW ONLY; 

Prompt Jalu Chaudhary