PROMPT Jalu Chaudhary

CREATE TABLE VENDOR_PRODUCT (
    VEND_NUMBER NUMBER (5),
    PROD_CODE NUMBER(5),
    PRIMARY KEY (VEND_NUMBER, PROD_CODE),
    FOREIGN KEY (VEND_NUMBER) REFERENCES VENDOR(VEND_NUMBER),
    FOREIGN KEY (PROD_CODE) REFERENCES PRODUCT (PROD_CODE)
);

ALTER TABLE PRODUCT
ADD CONSTRAINT unique_prod_desc UNIQUE (PROD_DESC);
 
ALTER TABLE STUDENT
ADD CONSTRAINT CHECK_ST_DOB
CHECK(ST_DOB< TO_DATE( '01-JAN-2000', 'DD-MON-YYYY'));