CREATE TABLE JALU_CHAUDHARY(
    ID NUMBRE PRIMARY KEY,
    FIRST_NAME VARCHAR2 (50),
    LAST_NAME CHAR (20),
    DATE_OF_BIRTH DATE,
    EMAIL VARCHAR2(100)

);
SELECT table_name 
FROM user_tables; 
ALTER TABLE JALU_CHAUDHARY 
MODIFY LAST_NAME CHAR(25);
ALTER TABLE JALU_CHAUDHARY
DROP COLUMN DATE_OF_BIRTH;
RENAME JALU_CHAUDHARY TO JALU_TABLE;
DROP TABLE JALU_TABLE;
FLASHBACK TABLE JALU_TABLE TO BEFORE DROP;
DROP TABLE JALU_TABLE PURGE;
SELECT object_name, original_name 
FROM recyclebin;